### ISSUE TITLE
How to skip ssl verify 

### ISSUE THREAD

**Issue by chatchaisi** [Aiven-Open/http-connector-for-apache-kafka#216]
Problem : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 

I read all config but not found config for skip ssl verify on aiven http sink connector. 
Please help me to skip ssl verify(self-sign certificate). Thank you.

**Comment by jeqo** [comment]
@chatchaisi thanks for opening this issue. 

We don't want to encourage disabling SSL, but I understand it may be needed for testing environments. Could you consider the following options:

- Add self-signed certificate to your truststore (recommended)
- Disable it via JVM flag: `-Djdk.internal.httpclient.disableHostnameVerification=true` 

Let us know if any of these approaches are enough

cc @bucioo to also test these approaches.

**Comment by bucioo** [comment]
@jeqo, disabling via JVM didn't work for me as PKIX error is still visible. 
Regarding certificates, which trustsotre is being used? There is no option to add trustore directory in the configuration and adding it via JVM also didn't work. Any other suggestions?

**Comment by chatchaisi** [comment]
@jeqo I use self-sign as private network. and @bucioo say not work. I will test with your options and response to you after new year. 

Thank for your response to me.

**Comment by chatchaisi** [comment]
@jeqo  I tried to use `-Djdk.internal.httpclient.disableHostnameVerification=true` and `-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true` are not work for me. 

Do you have other way to config this? We have some problem to add self-signed certificate to my truststore.

**Comment by jeqo** [comment]
Thank you both for trying out! 
I have added a configuration to support disabling certificate verification by trusting all certificates: https://github.com/Aiven-Open/http-connector-for-apache-kafka/pull/223 could you give a try?

**Comment by chatchaisi** [comment]
I will try tmr. Thank you for this feature.

**Comment by bucioo** [comment]
@jeqo, this worked for me so i'm able to connect via https now. Obviously it's not perfect solution, ideally would be good to put in conf file truststore/keystore dirs with PW's. Would it be possible?

**Comment by jeqo** [comment]
@bucioo could you test adding truststore using [default connect configurations](https://docs.confluent.io/platform/current/connect/security.html#configuring-the-kconnect-rest-api-for-http-or-https)? My guess is that the `ssl.*` configs are shared by the whole worker process, including connector tasks. 
If that doesn't work, we can consider adding configurations for the http client independently.

**Comment by bucioo** [comment]
@jeqo, ssl.* confs are already in the connect properties file as tried that before adding to JVM itself but no luck. Looks like those are not passed

**Comment by chatchaisi** [comment]
@jeqo  Thank you for #223 . This branch is work.

**Comment by AnatolyPopov** [comment]
Implemented by https://github.com/Aiven-Open/http-connector-for-apache-kafka/pull/223
